nodeLinker: pnp
packageExtensions:
  "@next/env@*":
    dependencies:
      "@next/swc-darwin-arm64": "*"
      "@next/swc-darwin-x64": "*"
      "@next/swc-linux-arm64-gnu": "*"
      "@next/swc-linux-x64-gnu": "*"
      "@next/swc-win32-x64-msvc": "*"