cacheFolder: .yarn/cache
enableGlobalCache: true
nmHoistingLimits: workspaces
nodeLinker: pnp

packageExtensions:
  '@next/env@*':
    dependencies:
      '@next/swc-darwin-arm64': '*'
      '@next/swc-darwin-x64': '*'
      '@next/swc-linux-arm64-gnu': '*'
      '@next/swc-linux-x64-gnu': '*'
      '@next/swc-win32-x64-msvc': '*'
  lint-staged@*:
    peerDependencies:
      eslint: '*'
      prettier: '*'
  prettier@*:
    peerDependencies:
      '@prettier/plugin-php': '*'
      '@prettier/plugin-ruby': '*'
      '@prettier/plugin-xml': '*'
  eslint-plugin-import@*:
    dependencies:
      eslint-import-resolver-typescript: '*'
  '@typescript-eslint/parser@*':
    dependencies:
      typescript: '*'
  '@typescript-eslint/eslint-plugin@*':
    dependencies:
      typescript: '*'
